### ISSUE TITLE
Allow multiple maps for the same key

### ISSUE THREAD

**Issue by sp88011** [pyncz/zod-key-mapper#1]
First of all, this is a great library. I was looking a long time for a simple/elegant solution like this one. 

I think it would be useful if it was possible to map the same key more than once, e.g.

```
const schema = mapped(z.object({
  key1: z.string(),
  key2: z.number(),
  key3: z.number(),
}), 
{
key1: 'key1mod',
key2: ['key2mod', 'key2modSecondTime'] // <--maybe like so?
})
```

**Comment by pyncz** [comment]
Hi! Thanks for your interest in the package, really glad you found it useful

As for the suggestion, could you describe the expected behaviour for the schema above? I understand correctly that the field should be duplicated under the additional key, like this?
```ts
console.log(schema.parse({ key1: 'hey', key2: 1, key3: 42 }))
// > { key1: 'hey', key2mod: 1, key2modSecondTime: 1, key3: 42 }
```
If so, can't think of a suitable use case.

**Comment by sp88011** [comment]
Yes you got it.

I'm using Zod and your library for parsing, and so something like this would be helpful in creating an (output) object of a certain shape. There's obviously other ways to copy properties, but this would save a step.

**Comment by pyncz** [comment]
Oh. Honestly, duplicating props doesn't seem like a good idea... Either way, these are specific needs more related to further operations rather than parsing / transforming the input itself.
I think it's right to leave it out of the package.

But thanks for your involvement! :)
